# -*- coding: utf-8 -*-
"""Agglomerative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I-Sfbn4dQ-1qqSotTV24D1GVFFWYsHzA

**Segmentasi Tingkat Overstock Persediaan Produk Retail Menggunakan Agglomerative Clustering**

Cluster 0 — High Overstock
Cluster 1 — Moderate / Low Overstock
"""

# ==========================================================
# IMPORT LIBRARY
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score
)

from sklearn.decomposition import PCA

from scipy.cluster.hierarchy import dendrogram, linkage

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

# from google.colab import files

# uploaded = files.upload()

df = pd.read_csv("retail_store_inventory.csv")

df.shape

df.head()

df.info()
df.describe(include="all").T

"""**Data Cleaning**"""

df.isnull().sum()

df.duplicated().sum()

"""tipe data date menjadi datetime"""

df["Date"] = pd.to_datetime(df["Date"])

"""outlier

gunakan IQR
"""

numeric = df.select_dtypes(include=np.number)

for col in numeric.columns:

    Q1 = df[col].quantile(0.25)

    Q3 = df[col].quantile(0.75)

    IQR = Q3-Q1

    lower = Q1-1.5*IQR

    upper = Q3+1.5*IQR

    print(col,
          ((df[col]<lower)|(df[col]>upper)).sum())

"""Visualisasi"""

for col in numeric.columns:

    plt.figure(figsize=(6,2))

    sns.boxplot(
        x=df[col]
    )

    plt.title(col)

    plt.show()

"""**EDA**"""

numeric.hist(
    figsize=(15,10),
    bins=30
)

plt.show()

plt.figure(figsize=(10,8))

sns.heatmap(

    numeric.corr(),

    annot=True,

    cmap="coolwarm",

    fmt=".2f"

)

plt.show()

"""**Feature Engineering**"""

product_df = (

    df

    .groupby(

        [

            "Store ID",

            "Category",

            "Product ID"

        ],

        as_index=False

    )

    .agg({

        "Inventory Level":"mean",

        "Units Sold":"mean",

        "Units Ordered":"mean",

        "Demand Forecast":"mean",

        "Price":"mean",

        "Discount":"mean"

    })

)

"""Inventory Turnover"""

product_df["Inventory Turnover"] = (

    product_df["Units Sold"]

    /

    (product_df["Inventory Level"]+1)

)

"""Overstock Ratio"""

product_df["Overstock Ratio"] = (

    product_df["Inventory Level"]

    /

    (product_df["Demand Forecast"]+1)

)

"""Demand Gap"""

product_df["Demand Gap"] = (

    product_df["Demand Forecast"]

    -

    product_df["Inventory Level"]

)

"""Sell Through Rate"""

product_df["Sell Through Rate"] = (

    product_df["Units Sold"]

    /

    (product_df["Units Ordered"]+1)

)

"""**Semua Fitur**"""

features = [

    "Inventory Level",

    "Units Sold",

    "Units Ordered",

    "Demand Forecast",

    "Price",

    "Discount",

    "Inventory Turnover",

    "Overstock Ratio",

    "Demand Gap",

    "Sell Through Rate"

]

"""**Correlation Analysis**"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,8))

corr = product_df[features].corr()

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)

plt.show()

"""**Menghapus fitur dengan korelasi > 0.90**"""

import numpy as np

corr_matrix = product_df[features].corr().abs()

upper = corr_matrix.where(
    np.triu(
        np.ones(corr_matrix.shape),
        k=1
    ).astype(bool)
)

drop_features = [
    column
    for column in upper.columns
    if any(upper[column] > 0.90)
]

print("Fitur yang dihapus :")
print(drop_features)

"""**Update Feature**"""

features = [
    feature
    for feature in features
    if feature not in drop_features
]

print(features)

"""**Variance Threshold**"""

from sklearn.feature_selection import VarianceThreshold

selector = VarianceThreshold(
    threshold=0.01
)

X = product_df[features]

selector.fit(X)

selected = X.columns[
    selector.get_support()
]

features = list(selected)

print("Fitur setelah Variance Threshold")
print(features)

"""**Standardisasi**"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    product_df[features]
)

"""**PCA Loading**"""

pca = PCA()

pca.fit(X_scaled)

"""Loading Matrix"""

loading = pd.DataFrame(

    pca.components_.T,

    index=features,

    columns=[
        f"PC{i+1}"
        for i in range(len(features))
    ]

)

loading

"""Hitung Importance"""

loading["Importance"] = loading.abs().sum(axis=1)

loading = loading.sort_values(
    "Importance",
    ascending=False
)

loading

"""**Pilih Top Feature PCA**"""

features = loading.head(6).index.tolist()

print(features)

"""**Sequential Forward Selection**"""

import itertools

from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import silhouette_score

results = []

"""Loop seluruh kombinasi fitur"""

for r in range(2, len(features)+1):

    for subset in itertools.combinations(features, r):

        subset = list(subset)

        scaler = StandardScaler()

        X_scaled = scaler.fit_transform(
            product_df[subset]
        )

        model = AgglomerativeClustering(

            n_clusters=3,

            linkage="ward"

        )

        labels = model.fit_predict(
            X_scaled
        )

        sil = silhouette_score(
            X_scaled,
            labels
        )

        results.append([

            subset,

            sil

        ])

"""**Ranking**"""

result_df = pd.DataFrame(

    results,

    columns=[

        "Features",

        "Silhouette"

    ]

)

result_df = result_df.sort_values(

    "Silhouette",

    ascending=False

)

result_df.head(20)

"""**Ambil Kombinasi Terbaik**"""

best_features = list(
    result_df.iloc[0]["Features"]
)

print(best_features)

"""**DEndogram**"""

plt.figure(figsize=(12,6))

linkage_matrix = linkage(
    X_scaled,
    method="ward"
)

dendrogram(
    linkage_matrix,
    truncate_mode="level",
    p=5
)

plt.title("Dendrogram")

plt.show()

"""**Clustering Final**"""

scaler = StandardScaler()

X_scaled = scaler.fit_transform(
    product_df[best_features]
)

model = AgglomerativeClustering(

    n_clusters=2,

    linkage="ward"

)

labels = model.fit_predict(
    X_scaled
)

product_df["Cluster"] = labels

"""**Evaluasi**"""

from sklearn.metrics import (

    silhouette_score,

    davies_bouldin_score,

    calinski_harabasz_score

)

print("Silhouette Score :",

      round(

          silhouette_score(

              X_scaled,

              labels

          ),

          4

      ))

print("Davies Bouldin :",

      round(

          davies_bouldin_score(

              X_scaled,

              labels

          ),

          4

      ))

print("Calinski Harabasz :",

      round(

          calinski_harabasz_score(

              X_scaled,

              labels

          ),

          4

      ))

cluster_profile = (

    product_df

    .groupby("Cluster")[best_features]

    .mean()

)

cluster_profile.round(2)

product_df["Cluster"].value_counts()

segmentasi = product_df[

    [

        "Store ID",

        "Category",

        "Product ID",

        "Cluster"

    ]

]

segmentasi.head(20)

# ==========================================================
# VISUALISASI CLUSTER
# ==========================================================

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,7))

sns.scatterplot(
    data=product_df,
    x="Demand Gap",
    y="Inventory Level",
    hue="Cluster",
    palette="Set1",
    s=100,
    edgecolor="black"
)

plt.title("Visualisasi Agglomerative Clustering", fontsize=15)
plt.xlabel("Demand Gap")
plt.ylabel("Inventory Level")

plt.legend(title="Cluster")

plt.show()

# ==========================================================
# TITIK TENGAH CLUSTER
# ==========================================================

centroid = product_df.groupby("Cluster")[
    ["Demand Gap","Inventory Level"]
].mean()

plt.figure(figsize=(10,7))

sns.scatterplot(
    data=product_df,
    x="Demand Gap",
    y="Inventory Level",
    hue="Cluster",
    palette="Set1",
    s=90,
    edgecolor="black"
)

plt.scatter(
    centroid["Demand Gap"],
    centroid["Inventory Level"],
    s=400,
    marker="X",
    color="black",
    label="Cluster Center"
)

plt.title("Agglomerative Clustering")
plt.legend()

plt.show()

# ==========================================================
# JUMLAH DATA TIAP CLUSTER
# ==========================================================

cluster_count = product_df["Cluster"].value_counts().sort_index()

print(cluster_count)

"""**Visualisasi Jumlah Cluster**"""

plt.figure(figsize=(6,4))

sns.countplot(
    data=product_df,
    x="Cluster",
    palette="Set2"
)

plt.title("Jumlah Produk pada Setiap Cluster")

plt.xlabel("Cluster")

plt.ylabel("Jumlah Produk")

plt.show()

# ==========================================================
# PROFIL CLUSTER
# ==========================================================

cluster_profile = product_df.groupby("Cluster")[
    [
        "Demand Gap",
        "Inventory Level"
    ]
].mean().round(2)

cluster_profile

"""**Distribusi Store pada Tiap Cluster**"""

pd.crosstab(
    product_df["Store ID"],
    product_df["Cluster"]
)

"""**Distribusi Category pada Tiap Cluster**"""

pd.crosstab(
    product_df["Category"],
    product_df["Cluster"]
)

"""**Distribusi Produk pada Tiap Cluster**"""

pd.crosstab(
    product_df["Product ID"],
    product_df["Cluster"]
)

"""**Menampilkan Hasil Segmentasi**"""

segmentasi = product_df[
    [
        "Store ID",
        "Category",
        "Product ID",
        "Demand Gap",
        "Inventory Level",
        "Cluster"
    ]
]

segmentasi.head(20)

"""**Menampilkan Anggota Tiap Cluster**"""

for i in sorted(product_df["Cluster"].unique()):

    print("="*60)
    print(f"CLUSTER {i}")
    print("="*60)

    print(
        product_df[
            product_df["Cluster"]==i
        ][
            [
                "Store ID",
                "Category",
                "Product ID",
                "Demand Gap",
                "Inventory Level"
            ]
        ]
    )

# ==========================================================
# BOXPLOT PER CLUSTER
# ==========================================================

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

sns.boxplot(
    data=product_df,
    x="Cluster",
    y="Demand Gap",
    ax=axes[0]
)
axes[0].set_title("Demand Gap per Cluster")

sns.boxplot(
    data=product_df,
    x="Cluster",
    y="Inventory Level",
    ax=axes[1]
)
axes[1].set_title("Inventory Level per Cluster")

plt.tight_layout()
plt.show()

# ==========================================================
# PENAMAAN CLUSTER
# ==========================================================

cluster_name = {

    0: "High Overstock",

    1: "Moderate Overstock"

}

product_df["Cluster Name"] = product_df["Cluster"].map(cluster_name)

# ==========================================================
# REKOMENDASI
# ==========================================================

recommendation = {

    "High Overstock":
    """
    Mengurangi jumlah pemesanan pada periode berikutnya,
    melakukan promosi atau diskon untuk mempercepat penjualan,
    menerapkan bundling produk,
    mengevaluasi reorder point,
    dan meningkatkan akurasi demand forecasting.
    """,

    "Moderate Overstock":
    """
    Mempertahankan strategi persediaan saat ini,
    melakukan monitoring permintaan secara berkala,
    menyesuaikan jumlah pembelian berdasarkan tren penjualan,
    serta melakukan evaluasi forecasting secara periodik.
    """

}

product_df["Recommendation"] = product_df["Cluster Name"].map(recommendation)

product_df[[
    "Store ID",
    "Category",
    "Product ID",
    "Demand Gap",
    "Inventory Level",
    "Cluster",
    "Cluster Name",
    "Recommendation"
]].head(20)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,5))

sns.countplot(

    data=product_df,

    x="Cluster Name",

    palette="Set2",

    order=product_df["Cluster Name"].value_counts().index

)

plt.title("Jumlah Produk pada Setiap Segmentasi")

plt.xlabel("Segmentasi Produk")

plt.ylabel("Jumlah Produk")

plt.xticks(rotation=10)

plt.show()

# ==========================================================
# SIMPAN HASIL CLUSTER
# ==========================================================

product_df.to_csv(
    "Hasil_Agglomerative_Clustering.csv",
    index=False
)

print("File berhasil disimpan")