# -*- coding: utf-8 -*-
"""revisi_Agglomerative_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RV-PzxpBK4A88WcefwinKLflzLsWYmwl

**Segmentasi Tingkat Overstock Persediaan Produk Retail Menggunakan Agglomerative Clustering**

Cluster 0 — High Overstock
Cluster 1 — Moderate / Low Overstock
"""

# ==========================================================
# IMPORT LIBRARY
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler

from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import (
    silhouette_score,
    davies_bouldin_score,
    calinski_harabasz_score
)

from sklearn.decomposition import PCA

from scipy.cluster.hierarchy import dendrogram, linkage

plt.style.use("ggplot")
sns.set_theme(style="whitegrid")

from google.colab import files

uploaded = files.upload()

df = pd.read_csv("/content/retail_store_inventory.csv")

# ==========================================================
# 3.1 UKURAN DATASET
# ==========================================================

print("Jumlah Baris :", df.shape[0])
print("Jumlah Kolom :", df.shape[1])

# ==========================================================
# 3.2 MENAMPILKAN 5 DATA PERTAMA
# ==========================================================

df.head()

# ==========================================================
# 3.4 INFORMASI DATASET
# ==========================================================

df.info()

# ==========================================================
# 3.5 STATISTIK DESKRIPTIF
# ==========================================================

df.describe().T

# ==========================================================
# 3.6 NAMA KOLOM
# ==========================================================

print(df.columns.tolist())

# ==========================================================
# 3.7 TIPE DATA
# ==========================================================

df.dtypes

# ==========================================================
# 3.8 MISSING VALUE
# ==========================================================

missing = pd.DataFrame({

    "Missing Value": df.isnull().sum(),

    "Persentase (%)": round(df.isnull().mean()*100,2)

})

missing

# ==========================================================
# VISUALISASI MISSING VALUE
# ==========================================================

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

sns.heatmap(
    df.isnull(),
    cbar=False,
    yticklabels=False,
    cmap="viridis"
)

plt.title("Visualisasi Missing Value")

plt.show()

# ==========================================================
# DATA DUPLIKAT
# ==========================================================

duplicate = df.duplicated().sum()

print("Jumlah Data Duplikat :", duplicate)

# ==========================================================
# NILAI UNIK TIAP KOLOM
# ==========================================================

unique = pd.DataFrame({

    "Jumlah Nilai Unik": df.nunique()

})

unique

# ==========================================================
# NILAI KATEGORI
# ==========================================================

categorical_columns = [

    "Store ID",

    "Product ID",

    "Category",

    "Region",

    "Weather Condition",

    "Holiday/Promotion",

    "Seasonality"

]

for col in categorical_columns:

    print("="*60)

    print(col)

    print(df[col].value_counts())

    print()

# ==========================================================
# DISTRIBUSI FITUR NUMERIK
# ==========================================================

numeric_columns = df.select_dtypes(include=['int64','float64']).columns

df[numeric_columns].hist(
    figsize=(15,12),
    bins=30
)

plt.tight_layout()

plt.show()

# ==========================================================
# HEATMAP KORELASI
# ==========================================================

plt.figure(figsize=(12,10))

sns.heatmap(

    df.select_dtypes(include=['int64','float64']).corr(),

    annot=True,

    cmap="coolwarm",

    fmt=".2f"

)

plt.title("Heatmap Korelasi")

plt.show()

# ==========================================================
# 4.1 COPY DATASET
# ==========================================================

df_clean = df.copy()

print(df_clean.shape)

# ==========================================================
# 4.2 CEK MISSING VALUE
# ==========================================================

missing = pd.DataFrame({
    "Missing": df_clean.isnull().sum(),
    "Persentase (%)": round(df_clean.isnull().mean()*100,2)
})

missing

# ==========================================================
# IMPUTASI NUMERIK
# ==========================================================

from sklearn.impute import SimpleImputer

numeric_cols = df_clean.select_dtypes(include=["int64","float64"]).columns

imputer_num = SimpleImputer(strategy="median")

df_clean[numeric_cols] = imputer_num.fit_transform(df_clean[numeric_cols])

# ==========================================================
# IMPUTASI KATEGORIKAL
# ==========================================================

categorical_cols = df_clean.select_dtypes(include=["object"]).columns

imputer_cat = SimpleImputer(strategy="most_frequent")

df_clean[categorical_cols] = imputer_cat.fit_transform(df_clean[categorical_cols])

print(df_clean.isnull().sum())

# ==========================================================
# DUPLIKAT
# ==========================================================

print("Sebelum :", df_clean.shape)

df_clean.drop_duplicates(inplace=True)

print("Sesudah :", df_clean.shape)

# ==========================================================
# KONVERSI DATE
# ==========================================================

df_clean["Date"] = pd.to_datetime(df_clean["Date"])

df_clean["Year"] = df_clean["Date"].dt.year

df_clean["Month"] = df_clean["Date"].dt.month

df_clean["Day"] = df_clean["Date"].dt.day

df_clean.drop(columns="Date", inplace=True)

df_clean.head()

# ==========================================================
# LABEL ENCODING
# ==========================================================

from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

cat_columns = [

    "Store ID",
    "Product ID",
    "Category",
    "Region",
    "Weather Condition",
    "Holiday/Promotion",
    "Seasonality"

]

for col in cat_columns:

    df_clean[col] = encoder.fit_transform(df_clean[col].astype(str))

df_clean.head()

# ==========================================================
# TIPE DATA
# ==========================================================

df_clean.dtypes

# ==========================================================
# BOXPLOT
# ==========================================================

import matplotlib.pyplot as plt

numeric_cols = df_clean.select_dtypes(include=["int64","float64"]).columns

for col in numeric_cols:

    plt.figure(figsize=(6,3))

    plt.boxplot(df_clean[col], vert=False)

    plt.title(col)

    plt.show()

# ==========================================================
# PENANGANAN OUTLIER
# ==========================================================

for col in numeric_cols:

    Q1 = df_clean[col].quantile(0.25)

    Q3 = df_clean[col].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR

    upper = Q3 + 1.5 * IQR

    df_clean[col] = df_clean[col].clip(lower, upper)

print("Outlier berhasil ditangani.")

for col in numeric_cols:

    plt.figure(figsize=(6,3))

    plt.boxplot(df_clean[col], vert=False)

    plt.title(col)

    plt.show()

print(df_clean.shape)

df_clean.head()

# ==========================================================
# STORE
# ==========================================================

plt.figure(figsize=(6,4))

sns.countplot(
    data=df_clean,
    x="Store ID"
)

plt.title("Distribusi Store")

plt.show()

# ==========================================================
# CATEGORY
# ==========================================================

plt.figure(figsize=(7,4))

sns.countplot(
    data=df_clean,
    x="Category"
)

plt.title("Distribusi Category")

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# REGION
# ==========================================================

plt.figure(figsize=(7,4))

sns.countplot(
    data=df_clean,
    x="Region"
)

plt.title("Distribusi Region")

plt.show()

# ==========================================================
# WEATHER
# ==========================================================

plt.figure(figsize=(6,4))

sns.countplot(
    data=df_clean,
    x="Weather Condition"
)

plt.title("Distribusi Weather")

plt.show()

# ==========================================================
# SEASONALITY
# ==========================================================

plt.figure(figsize=(6,4))

sns.countplot(
    data=df_clean,
    x="Seasonality"
)

plt.title("Distribusi Seasonality")

plt.show()

# ==========================================================
# INVENTORY vs CATEGORY
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(

    x="Category",

    y="Inventory Level",

    data=df_clean

)

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# SALES vs CATEGORY
# ==========================================================

plt.figure(figsize=(8,5))

sns.boxplot(

    x="Category",

    y="Units Sold",

    data=df_clean

)

plt.xticks(rotation=45)

plt.show()

# ==========================================================
# INVENTORY vs STORE
# ==========================================================

plt.figure(figsize=(7,4))

sns.boxplot(

    x="Store ID",

    y="Inventory Level",

    data=df_clean

)

plt.show()

# ==========================================================
# SALES vs STORE
# ==========================================================

plt.figure(figsize=(7,4))

sns.boxplot(

    x="Store ID",

    y="Units Sold",

    data=df_clean

)

plt.show()

# ==========================================================
# INVENTORY vs SALES
# ==========================================================

plt.figure(figsize=(8,6))

sns.scatterplot(

    data=df_clean,

    x="Inventory Level",

    y="Units Sold",

    alpha=0.5

)

plt.title("Inventory Level vs Units Sold")

plt.show()

# ==========================================================
# DEMAND vs SALES
# ==========================================================

plt.figure(figsize=(8,6))

sns.scatterplot(

    data=df_clean,

    x="Demand Forecast",

    y="Units Sold",

    alpha=0.5

)

plt.show()

# ==========================================================
# 6.1 MENENTUKAN FITUR
# ==========================================================

features = df_clean.columns.tolist()

print("Jumlah fitur :", len(features))
print(features)

# ==========================================================
# 6.2 MEMBENTUK DATA FITUR
# ==========================================================

X = df_clean[features]

print(X.shape)

X.head()

# ==========================================================
# 6.3 CEK MISSING VALUE
# ==========================================================

print(X.isnull().sum())

print()

print("Total Missing :", X.isnull().sum().sum())

# ==========================================================
# 6.4 STANDARDISASI
# ==========================================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled.shape)

# ==========================================================
# DATAFRAME HASIL STANDARDISASI
# ==========================================================

X_scaled = pd.DataFrame(

    X_scaled,

    columns=features

)

X_scaled.head()

# ==========================================================
# CEK HASIL STANDARDISASI
# ==========================================================

X_scaled.describe().T

# ==========================================================
# TRAIN TEST SPLIT
# ==========================================================

from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(

    X_scaled,

    test_size=0.2,

    random_state=42,

    shuffle=True

)

print("Train :", X_train.shape)

print("Test  :", X_test.shape)

# ==========================================================
# CEK UKURAN DATA
# ==========================================================

print("Train")

display(X_train.describe().T)

print("Test")

display(X_test.describe().T)

# ==========================================================
# COPY DATA
# ==========================================================

train_data = X_train.copy()

test_data = X_test.copy()

print("="*50)

print("Jumlah fitur :", len(features))

print("Jumlah data train :", X_train.shape[0])

print("Jumlah data test :", X_test.shape[0])

print("="*50)

# ==========================================================
# AGREGASI DATA
# ==========================================================

product_df = (

    df_clean

    .groupby(

        [

            "Store ID",

            "Product ID"

        ]

    )

    .agg({

        "Category":"first",

        "Region":"first",

        "Inventory Level":"mean",

        "Units Sold":"sum",

        "Units Ordered":"sum",

        "Demand Forecast":"mean",

        "Price":"mean",

        "Discount":"mean",

        "Weather Condition":"first",

        "Holiday/Promotion":"mean",

        "Competitor Pricing":"mean",

        "Seasonality":"first",

        "Year":"first",

        "Month":"mean",

        "Day":"mean"

    })

    .reset_index()

)

print(product_df.shape)

product_df.isnull().sum()

features = product_df.columns.tolist()

print(features)

X = product_df[features]

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test = train_test_split(

    X_scaled,

    test_size=0.2,

    random_state=42

)

print(X_train.shape)

print(X_test.shape)

from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram

import matplotlib.pyplot as plt

Z = linkage(

    X_train,

    method="ward"

)

plt.figure(figsize=(15,6))

dendrogram(Z)

plt.title("Dendrogram")

plt.show()

from sklearn.cluster import AgglomerativeClustering

from sklearn.metrics import silhouette_score

from sklearn.metrics import davies_bouldin_score

from sklearn.metrics import calinski_harabasz_score

results = []

for k in range(2,21):

    model = AgglomerativeClustering(

        n_clusters=k,

        linkage="ward"

    )

    labels = model.fit_predict(X_train)

    sil = silhouette_score(X_train, labels)

    dbi = davies_bouldin_score(X_train, labels)

    chi = calinski_harabasz_score(X_train, labels)

    results.append([k,sil,dbi,chi])

result_df = pd.DataFrame(

    results,

    columns=[

        "K",

        "Silhouette",

        "DBI",

        "CHI"

    ]

)

result_df

model = AgglomerativeClustering(

    n_clusters=2,

    linkage="ward"

)

product_df["Cluster"] = model.fit_predict(X_scaled)

product_df.head()

cluster_name = {

    0:"High Overstock",

    1:"Moderate Overstock"

}

product_df["Segment"] = product_df["Cluster"].map(cluster_name)

result = product_df[

    [

        "Store ID",

        "Product ID",

        "Category",

        "Cluster",

        "Segment"

    ]

].sort_values(

    [

        "Store ID",

        "Product ID"

    ]

)

display(result)

# ==========================================================
# MENAMPILKAN HASIL CLUSTER PER STORE
# ==========================================================

for store in sorted(product_df["Store ID"].unique()):

    print("=" * 70)
    print(f"STORE {store}")
    print("=" * 70)

    display(

        product_df[
            product_df["Store ID"] == store
        ][
            [
                "Store ID",
                "Product ID",
                "Category",
                "Cluster",
                "Segment"
            ]
        ].sort_values("Product ID")

    )

for store in sorted(product_df["Store ID"].unique()):

    print("=" * 70)
    print(f"STORE {store}")
    print("=" * 70)

    print(
        product_df[
            product_df["Store ID"] == store
        ][
            [
                "Store ID",
                "Product ID",
                "Category",
                "Cluster",
                "Segment"
            ]
        ].sort_values("Product ID")
    )

    print("\n")

